name: Release Dock

on:
  release:
    types: [published]

jobs:
  update-homebrew-tap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Get release version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: Calculate SHA-256
        id: sha256
        run: |
          curl -L "https://github.com/geeth24/dock/archive/${{ steps.get_version.outputs.version }}.tar.gz" -o dock.tar.gz
          echo "::set-output name=sha256::$(shasum -a 256 dock.tar.gz | cut -d' ' -f1)"

      - name: Checkout Homebrew Tap Repository
        uses: actions/checkout@v2
        with:
          repository: geeth24/homebrew-dock
          path: homebrew-tap

      - name: Update Homebrew Formula
        run: |
          sed -i "s|url \".*\"|url \"https://github.com/geeth24/dock/archive/${{ steps.get_version.outputs.version }}.tar.gz\"|" homebrew-tap/dock.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.sha256.outputs.sha256 }}\"|" homebrew-tap/dock.rb

      - name: Commit and push changes to Homebrew Tap
        run: |
          cd homebrew-tap
          git config --local user.email "geeth.gunnampalli@gmail.com"
          git config --local user.name "Geeth Gunampalli"
          git commit -am "Update Dock to version ${{ steps.get_version.outputs.version }}"
          git push origin main
